version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: olake-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: olake_orders
      MYSQL_USER: olake_user
      MYSQL_PASSWORD: olake_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest-catalog
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=/tmp/warehouse
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    depends_on:
      - minio

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    entrypoint: bash
    command: -c 'mkdir -p /data/warehouse && minio server /data --console-address ":9001"'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  spark:
    image: spark-iceberg:simple
    container_name: spark-iceberg
    ports:
      - "4040:4040"
    volumes:
      - ./:/workspace
    environment:
      - SPARK_LOCAL_IP=0.0.0.0
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    depends_on:
      - iceberg-rest
      - minio

volumes:
  mysql_data:
  minio_data:
